version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"

